### ISSUE TITLE
Create THIRDPARTY.md

### ISSUE THREAD

**Issue by kneckinator** [idpass/mimoto#14]
The `pom.xml` references a set of dependencies and there needs to be a report in a file `THIRDPARTY.md` that is matching the current set of dependencies, showing the names of the dependencies and their licenses.

We need to disclose and acknowledge these licenses.

There is a dependency https://maven.apache.org/plugins/maven-dependency-plugin/ that can generate dependency reports automatically and we could use to generate the content.

**Comment by jeremi** [comment]
ok, yes, let's do this!

**Comment by kneckinator** [comment]
@typelogic Could you take a look at this?

**Comment by typelogic** [comment]
Initial maven-automated gathering of [Licenses detailed report](https://drive.google.com/file/d/1QJ0tAfW8kxMlV0vEmHu8gUsAhWoRXCiY/view?usp=sharing)

**Comment by jeremi** [comment]
Can it generate a Markdown file?

**Comment by typelogic** [comment]
> Can it generate a Markdown file?

I tried to convert to markdown format https://gist.github.com/9e1a0c735c5c4ed14acaab86cbccec9d using python script below:

```
import markdownify
html = open('target/site/dependencies.html').read()
md = markdownify.markdownify(html, heading_style="ATX")
open('THIRDPARTY.md','w').write(md)
```

**Comment by kneckinator** [comment]
Looks good @typelogic
