### ISSUE TITLE
Support lock/unlock biometric authentication in the app backend

### ISSUE THREAD

**Issue by kneckinator** [idpass/mimoto#16]
We need to provide API:s for the mobile app that allows it to:
- Lock an auth factor
- Unlock an auth factor
- Check the "lock status" of an auth factor (to be discussed)

All discussions around the feature are happening in https://github.com/idpass/inji/issues/133

**Comment by kneckinator** [comment]
Assigning this to you @typelogic for the backend changes so you can have it as a reference for your upcoming mimoto-PR.

**Comment by typelogic** [comment]
After Madhu added `bio` in the config for Resident app and then she restarted subsystems, I resent same request and now getting success json response: 

```
{
    "id": "mosip.resident.authlock",
    "version": "v1",
    "str": null,
    "responsetime": "2022-04-13T06:39:51.437Z",
    "metadata": null,
    "response": {
        "status": null,
        "message": "Notification has been sent to the provided contact detail(s)"
    },
    "errors": null
}
```
