### ISSUE TITLE
Print version and git commit hash when service start

### ISSUE THREAD

**Issue by uocnb** [idpass/mimoto#19]
**Is your feature request related to a problem? Please describe.**
It is hard to verify what's version is running without check the jar file.

**Describe the solution you'd like**
Print version and git commit hash when service start, so we can check the log when service is running.

**Comment by kneckinator** [comment]
This was merged to `develop` just now. We had not tagged this issue with a milestone. Noting that we're not sharing milestones 1:1 between mimoto/inji at the moment.
Maybe we should have a milestone like `mimoto-0.2.1` for this so we don't confuse the two for QA?

**Comment by uocnb** [comment]
@kneckinator yes, we should keep the same major version for both backend and frontend, changing only minor version is good :+1:
