### ISSUE TITLE
Add endpoint to allow Inji to retrieve version string of Mimoto and which MOSIP server Mimoto is connected to

### ISSUE THREAD

**Issue by kneckinator** [idpass/mimoto#30]
To make it clear which backend the mobile app (Inji) is connected to, there should be an API endpoint to retrieve the version string of Mimoto.

To make is clear which MOSIP server Mimoto is configured to use, there should be an API endpoint to retrieve the URL/URI.

**Why is this needed?**
This is needed to bring clarity to the SUT (System Under Test) and enable all involved to clearly see this.

**Comment by uocnb** [comment]
New API: /info

Sample response:
```json
{
    "application": {
        "name": "mimoto",
        "version": "0.2.0-SNAPSHOT"
    },
    "build": {
        "git.tags": "",
        "git.commit.id.abbrev": "ce5aee0",
        "git.branch": "feature/30-Version-info-and-build-properties-api",
        "git.build.time": "2022-05-25T12:37:46+0700"
    },
    "config": {
        "mosip.host": "https://qa-triple-rc2.mosip.net",
        "websub.url": "https://qa-triple-rc2.mosip.net/hub/"
    }
}
```
